version: '3.8'
services:
 par-api:
    container_name: parfet-api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '8000:8000'
    env_file:
      - .env
