version: '3.8'
services:
 par-api:
    container_name: parfet-api-consumer-staging
    build:
      context: .
      dockerfile: Dockerfile.staging
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '8002:8002'
    env_file:
      - .env
