name: Deploy Parfet-Backend-Consumer Application [Development]

on:
  push:
    branches: [ develop ]

jobs:
  Deploy:
    needs: preparing
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: Create .env file
        run : |
          touch .env
          echo "${{ secrets.DEV_API_ENV }}" >> .env
          touch aws.pem
          echo "${{ secrets.SSH_PEM_KEY }}" >> aws.pem
          sudo chmod 440 aws.pem
          ls -la
          
      - name: Cloning repository
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{secrets.SSH_PEM_KEY}}
          script: |
           rm -rf PAR-Backend-Consumer || :
           git clone git@github.com:Parfet/PAR-Backend-Consumer.git

      - name: COPY .env 
        run : |
          ls -la
          scp -i "aws.pem" .env ${{ secrets.SSH_USERNAME }}@${{secrets.SSH_HOST}}:~/PAR-Backend-Consumer/

      - name: Deploy Application
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{secrets.SSH_PEM_KEY}}
          script: |
           cd PAR-Backend-Consumer
           docker-compose down --rmi local || :
           docker-compose up -d --build
           docker ps -a